# Generated by Django 6.0.2 on 2026-02-23 03:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0008_delete_caseperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_case', models.CharField(choices=[('complainant', 'Complainant'), ('witness', 'Witness'), ('suspect', 'Suspect'), ('victim', 'Victim'), ('other', 'Other')], default='other', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_people', to='cases.case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_roles', to='accounts.person')),
            ],
            options={
                'unique_together': {('case', 'person', 'role_in_case')},
            },
        ),
    ]
