# Generated by Django 6.0.2 on 2026-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('administrator', 'Administrator'), ('cadet', 'Cadet'), ('police officer', 'Police Officer'), ('patrol officer', 'Patrol Officer'), ('detective', 'Detective'), ('sergeant', 'Sergeant'), ('captain', 'Captain'), ('chief', 'Chief'), ('complainant', 'Complainant'), ('coroner', 'Coroner'), ('judge', 'Judge')], max_length=32),
        ),
    ]
