# Generated by Django 6.0.2 on 2026-02-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_extra_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='extra_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
