# Generated by Django 4.2.28 on 2026-02-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_person_national_id_user_photo'),
        ('accounts', '0009_add_suspect_role'),
        ('accounts', '0011_merge_0008_0010'),
    ]

    operations = [
    ]
