# Generated by Django 4.2.28 on 2026-02-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_ensure_person_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('administrator', 'Administrator'), ('cadet', 'Cadet'), ('police officer', 'Police Officer'), ('patrol officer', 'Patrol Officer'), ('detective', 'Detective'), ('sergeant', 'Sergeant'), ('captain', 'Captain'), ('chief', 'Chief'), ('complainant', 'Complainant'), ('coroner', 'Coroner'), ('judge', 'Judge'), ('suspect', 'Suspect')], max_length=32),
        ),
    ]
