# Generated by Django 6.0.2 on 2026-02-23 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_caseperson'),
        ('cases', '0008_delete_caseperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('verdict', models.CharField(choices=[('guilty', 'Guilty'), ('not_guilty', 'Not Guilty'), ('mistrial', 'Mistrial'), ('other', 'Other')], default='other', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('court_room', models.CharField(blank=True, max_length=128)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='cases.case')),
                ('witnesses', models.ManyToManyField(blank=True, related_name='trial_witnesses', to='accounts.person')),
            ],
        ),
    ]
