# Generated by Django 4.2.28 on 2026-02-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0002_add_interrogation_suspect'),
        ('trials', '0002_trial_judge_and_more'),
    ]

    operations = [
    ]
