# Generated by Django 6.0.2 on 2026-02-23 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0002_attachment_crimereport_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('document', 'Document'), ('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d')),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('chain_of_custody', models.JSONField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('logged', 'Logged'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('released', 'Released')], default='logged', max_length=32)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(blank=True, max_length=255)),
                ('file_format', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_detail', to='evidence.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='BiologicalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biopsy_result', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Coroner Review'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('images', models.ManyToManyField(blank=True, related_name='biological_images', to='cases.attachment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biological_reviews', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biological_detail', to='evidence.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_value_pairs', models.JSONField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identification_detail', to='evidence.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('transcript', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('admitted', 'Admitted'), ('denied', 'Denied'), ('confession', 'Confession'), ('inconclusive', 'Inconclusive'), ('other', 'Other')], default='other', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_interrogations', to='accounts.person')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrogations', to='cases.case')),
                ('suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrogations', to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(blank=True, max_length=64)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_detail', to='evidence.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=128)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_detail', to='evidence.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimony_detail', to='evidence.evidence')),
                ('witness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=128)),
                ('license_plate', models.CharField(blank=True, max_length=64)),
                ('vin', models.CharField(blank=True, max_length=128)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_detail', to='evidence.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, max_length=128)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_detail', to='evidence.evidence')),
            ],
        ),
    ]
