# Generated by Django 6.0.2 on 2026-02-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalevidence',
            name='images',
        ),
    ]
