# Generated by Django 6.0.2 on 2026-02-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_remove_biologicalevidence_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interrogation',
        ),
    ]
