# Generated by Django 6.0.2 on 2026-02-23 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_attachment_interrogation'),
        ('evidence', '0003_delete_interrogation'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalevidence',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='biological_images', to='cases.attachment'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='related_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='cases.report'),
        ),
    ]
