# Generated by Django 6.0.2 on 2026-02-23 01:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('investigation', 'Investigation'), ('closed', 'Closed'), ('cold', 'Cold'), ('archived', 'Archived')], default='new', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('precinct', models.CharField(blank=True, max_length=64)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('witnesses', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_superior', 'Pending Superior Approval'), ('approved', 'Approved'), ('returned', 'Returned')], default='pending_superior', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_superior_reports', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crime_reports', to='cases.case')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crime_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('complaint', 'Complaint'), ('patrol', 'Patrol Report'), ('forensic', 'Forensic Report'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UNDER_PURSUIT', 'Under Pursuit'), ('HOT_PURSUIT', 'Hot Pursuit'), ('CAPTURED', 'Captured'), ('RELEASED', 'Released')], default='UNDER_PURSUIT', max_length=32)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('last_status_update', models.DateField(blank=True, null=True)),
                ('crime_degree', models.IntegerField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_entries', to='accounts.person')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CasePerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_case', models.CharField(choices=[('complainant', 'Complainant'), ('witness', 'Witness'), ('suspect', 'Suspect'), ('victim', 'Victim'), ('other', 'Other')], default='other', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_people', to='cases.case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_roles', to='accounts.person')),
            ],
            options={
                'unique_together': {('case', 'person', 'role_in_case')},
            },
        ),
    ]
