# Generated by Django 6.0.2 on 2026-02-23 02:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('note', models.TextField(blank=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='cases.case')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='cases.report')),
            ],
        ),
        migrations.AddField(
            model_name='crimereport',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='crime_report_attachments', to='cases.attachment'),
        ),
    ]
