# Generated by Django 6.0.2 on 2026-02-23 02:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_attachment_crimereport_attachments'),
        ('evidence', '0002_remove_biologicalevidence_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_identifier', models.CharField(blank=True, max_length=128)),
                ('action', models.CharField(max_length=128)),
                ('target_type', models.CharField(blank=True, max_length=128)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='attachments',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
