# Generated by Django 6.0.2 on 2026-02-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='crime_report_attachments', to='cases.attachment'),
        ),
    ]
