# Generated by Django 6.0.2 on 2026-02-23 03:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0005_crimereport_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('transcript', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('admitted', 'Admitted'), ('denied', 'Denied'), ('confession', 'Confession'), ('inconclusive', 'Inconclusive'), ('other', 'Other')], default='other', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_interrogations', to='accounts.person')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrogations', to='cases.case')),
                ('suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrogations', to='accounts.person')),
            ],
        ),
    ]
