# Generated by Django 6.0.2 on 2026-02-23 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_interrogation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='interrogation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='cases.interrogation'),
        ),
    ]
