# Generated by Django 6.0.2 on 2026-02-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_attachment_interrogation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CasePerson',
        ),
    ]
