# Generated by Django 6.0.2 on 2026-02-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_delete_caseperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-opened_at'], 'permissions': [('assign_detective', 'اختصاص کارآگاه به پرونده'), ('verify_evidence', 'تأیید شواهد پرونده'), ('issue_warrant', 'صدور حکم جلب برای مظنون'), ('close_case', 'بستن پرونده')]},
        ),
    ]
