# Generated by Django 6.0.2 on 2026-02-26 22:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_suspect_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrogation',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='start_date',
            field=models.DateField(default=accounts.models._today_date),
        ),
    ]
