# Generated by Django 4.2.28 on 2026-02-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_interrogation_status'),
        ('cases', '0013_interrogation_guilt_scores'),
        ('cases', '0013_interrogation_status'),
    ]

    operations = [
    ]
